// These constants are for this challenge purpose only

export const BASE_URL = 'https://api-dev.foodstyles.com/graphql';

export const ACCESS_TOKEN =
  'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQ1LCJ0eXBlIjoiQUNDRVNTIiwiaWF0IjoxNjU0MzM0NTM0LCJleHAiOjE2NTQ5MzkzMzR9.cn0Jc-Lthejnu5nWsGkDEHPbZ2Kj6qxN5mOYK_ryicOtHHE15FUKGQ-M8pLkZz6dl9QlNNAoKs3ZV2aKfyd7nS3CvFppM9qhlTAq9fcPvn78NQHeO2WWAqGdSbUYKPAwGr-kvyZ5uVg--vJMStRmffAlQX_H_-wrZaPOpXrCYH58fZjyv0fHl_iXpLRVTmbGmWsE-9QWQrUlb83T30xo2lHmF32_e9Edu5j1MzbjiYEZmodZ4bv2cSszz8NhCp9Us2hAGx6GeUdqZdZC_UlsNyYzGqvIZq7NudNQ1rt3tmYRBJpHy4I0TmOSxT_-GpHSOZJFeDcvc9pBvENmbEsI2w';
